/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorDashboardRouteImport } from './routes/tutor-dashboard'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PsychologyRouteImport } from './routes/psychology'
import { Route as PaperTradingRouteImport } from './routes/paper-trading'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveChartRouteImport } from './routes/live-chart'
import { Route as DematRouteImport } from './routes/demat'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BroadcastsRouteImport } from './routes/broadcasts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DematSlugRouteImport } from './routes/demat.$slug'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AuthRoleRegisterRouteImport } from './routes/auth.$role.register'
import { Route as AuthRoleLoginRouteImport } from './routes/auth.$role.login'

const TutorDashboardRoute = TutorDashboardRouteImport.update({
  id: '/tutor-dashboard',
  path: '/tutor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologyRoute = PsychologyRouteImport.update({
  id: '/psychology',
  path: '/psychology',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperTradingRoute = PaperTradingRouteImport.update({
  id: '/paper-trading',
  path: '/paper-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveChartRoute = LiveChartRouteImport.update({
  id: '/live-chart',
  path: '/live-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DematRoute = DematRouteImport.update({
  id: '/demat',
  path: '/demat',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsRoute = BroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DematSlugRoute = DematSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DematRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/admin/referrals',
  path: '/admin/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRegisterRoute = AuthRoleRegisterRouteImport.update({
  id: '/$role/register',
  path: '/$role/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoleLoginRoute = AuthRoleLoginRouteImport.update({
  id: '/$role/login',
  path: '/$role/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/auth': typeof AuthRouteWithChildren
  '/broadcasts': typeof BroadcastsRoute
  '/courses': typeof CoursesRoute
  '/demat': typeof DematRouteWithChildren
  '/live-chart': typeof LiveChartRoute
  '/login': typeof LoginRoute
  '/paper-trading': typeof PaperTradingRoute
  '/psychology': typeof PsychologyRoute
  '/quiz': typeof QuizRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screener': typeof ScreenerRoute
  '/signup': typeof SignupRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/tutor': typeof TutorRoute
  '/tutor-dashboard': typeof TutorDashboardRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/demat/$slug': typeof DematSlugRoute
  '/auth/$role/login': typeof AuthRoleLoginRoute
  '/auth/$role/register': typeof AuthRoleRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/auth': typeof AuthRouteWithChildren
  '/broadcasts': typeof BroadcastsRoute
  '/courses': typeof CoursesRoute
  '/demat': typeof DematRouteWithChildren
  '/live-chart': typeof LiveChartRoute
  '/login': typeof LoginRoute
  '/paper-trading': typeof PaperTradingRoute
  '/psychology': typeof PsychologyRoute
  '/quiz': typeof QuizRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screener': typeof ScreenerRoute
  '/signup': typeof SignupRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/tutor': typeof TutorRoute
  '/tutor-dashboard': typeof TutorDashboardRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/demat/$slug': typeof DematSlugRoute
  '/auth/$role/login': typeof AuthRoleLoginRoute
  '/auth/$role/register': typeof AuthRoleRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/auth': typeof AuthRouteWithChildren
  '/broadcasts': typeof BroadcastsRoute
  '/courses': typeof CoursesRoute
  '/demat': typeof DematRouteWithChildren
  '/live-chart': typeof LiveChartRoute
  '/login': typeof LoginRoute
  '/paper-trading': typeof PaperTradingRoute
  '/psychology': typeof PsychologyRoute
  '/quiz': typeof QuizRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screener': typeof ScreenerRoute
  '/signup': typeof SignupRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/tutor': typeof TutorRoute
  '/tutor-dashboard': typeof TutorDashboardRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/demat/$slug': typeof DematSlugRoute
  '/auth/$role/login': typeof AuthRoleLoginRoute
  '/auth/$role/register': typeof AuthRoleRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/auth'
    | '/broadcasts'
    | '/courses'
    | '/demat'
    | '/live-chart'
    | '/login'
    | '/paper-trading'
    | '/psychology'
    | '/quiz'
    | '/referrals'
    | '/reset-password'
    | '/screener'
    | '/signup'
    | '/student-dashboard'
    | '/tutor'
    | '/tutor-dashboard'
    | '/admin/referrals'
    | '/auth/callback'
    | '/auth/forgot'
    | '/demat/$slug'
    | '/auth/$role/login'
    | '/auth/$role/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/auth'
    | '/broadcasts'
    | '/courses'
    | '/demat'
    | '/live-chart'
    | '/login'
    | '/paper-trading'
    | '/psychology'
    | '/quiz'
    | '/referrals'
    | '/reset-password'
    | '/screener'
    | '/signup'
    | '/student-dashboard'
    | '/tutor'
    | '/tutor-dashboard'
    | '/admin/referrals'
    | '/auth/callback'
    | '/auth/forgot'
    | '/demat/$slug'
    | '/auth/$role/login'
    | '/auth/$role/register'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/auth'
    | '/broadcasts'
    | '/courses'
    | '/demat'
    | '/live-chart'
    | '/login'
    | '/paper-trading'
    | '/psychology'
    | '/quiz'
    | '/referrals'
    | '/reset-password'
    | '/screener'
    | '/signup'
    | '/student-dashboard'
    | '/tutor'
    | '/tutor-dashboard'
    | '/admin/referrals'
    | '/auth/callback'
    | '/auth/forgot'
    | '/demat/$slug'
    | '/auth/$role/login'
    | '/auth/$role/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuthRoute: typeof AuthRouteWithChildren
  BroadcastsRoute: typeof BroadcastsRoute
  CoursesRoute: typeof CoursesRoute
  DematRoute: typeof DematRouteWithChildren
  LiveChartRoute: typeof LiveChartRoute
  LoginRoute: typeof LoginRoute
  PaperTradingRoute: typeof PaperTradingRoute
  PsychologyRoute: typeof PsychologyRoute
  QuizRoute: typeof QuizRoute
  ReferralsRoute: typeof ReferralsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScreenerRoute: typeof ScreenerRoute
  SignupRoute: typeof SignupRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  TutorRoute: typeof TutorRoute
  TutorDashboardRoute: typeof TutorDashboardRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor-dashboard': {
      id: '/tutor-dashboard'
      path: '/tutor-dashboard'
      fullPath: '/tutor-dashboard'
      preLoaderRoute: typeof TutorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychology': {
      id: '/psychology'
      path: '/psychology'
      fullPath: '/psychology'
      preLoaderRoute: typeof PsychologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-trading': {
      id: '/paper-trading'
      path: '/paper-trading'
      fullPath: '/paper-trading'
      preLoaderRoute: typeof PaperTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-chart': {
      id: '/live-chart'
      path: '/live-chart'
      fullPath: '/live-chart'
      preLoaderRoute: typeof LiveChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demat': {
      id: '/demat'
      path: '/demat'
      fullPath: '/demat'
      preLoaderRoute: typeof DematRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts': {
      id: '/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof BroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demat/$slug': {
      id: '/demat/$slug'
      path: '/$slug'
      fullPath: '/demat/$slug'
      preLoaderRoute: typeof DematSlugRouteImport
      parentRoute: typeof DematRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$role/register': {
      id: '/auth/$role/register'
      path: '/$role/register'
      fullPath: '/auth/$role/register'
      preLoaderRoute: typeof AuthRoleRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/$role/login': {
      id: '/auth/$role/login'
      path: '/$role/login'
      fullPath: '/auth/$role/login'
      preLoaderRoute: typeof AuthRoleLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthRoleLoginRoute: typeof AuthRoleLoginRoute
  AuthRoleRegisterRoute: typeof AuthRoleRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthRoleLoginRoute: AuthRoleLoginRoute,
  AuthRoleRegisterRoute: AuthRoleRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DematRouteChildren {
  DematSlugRoute: typeof DematSlugRoute
}

const DematRouteChildren: DematRouteChildren = {
  DematSlugRoute: DematSlugRoute,
}

const DematRouteWithChildren = DematRoute._addFileChildren(DematRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuthRoute: AuthRouteWithChildren,
  BroadcastsRoute: BroadcastsRoute,
  CoursesRoute: CoursesRoute,
  DematRoute: DematRouteWithChildren,
  LiveChartRoute: LiveChartRoute,
  LoginRoute: LoginRoute,
  PaperTradingRoute: PaperTradingRoute,
  PsychologyRoute: PsychologyRoute,
  QuizRoute: QuizRoute,
  ReferralsRoute: ReferralsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScreenerRoute: ScreenerRoute,
  SignupRoute: SignupRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  TutorRoute: TutorRoute,
  TutorDashboardRoute: TutorDashboardRoute,
  AdminReferralsRoute: AdminReferralsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
